with-expecter: true
dir: "mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/tam/user-service/internal/repository:
    interfaces:
      UserRepository:
      SessionRepository:
  github.com/tam/user-service/internal/service:
    interfaces:
      AuthService:
      UserService:
